# Generated by Django 3.2.12 on 2022-10-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.FloatField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(max_length=9, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('Department', models.CharField(
                    default=1, max_length=100, null=True)),
                ('Semester', models.IntegerField(max_length=1, null=True)),
                ('date_created', models.DateTimeField(
                    auto_now_add=True, null=True)),
            ],
        ),
    ]
