# Generated by Django 4.1.7 on 2023-03-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Code')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Semester', models.IntegerField(null=True)),
                ('CreditHours', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_index', models.IntegerField(default='0', primary_key=True, serialize=False, verbose_name='student_index')),
                ('name', models.CharField(max_length=100, null=True)),
                ('Semester', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('CGPA', models.FloatField(null=True)),
                ('GPA', models.FloatField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.department')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mark', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('Z', 'Z')], max_length=50, null=True)),
                ('Semester', models.CharField(max_length=30, null=True)),
                ('Course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.course')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.department')),
                ('student_index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Login.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.department'),
        ),
    ]
