# Generated by Django 3.2.12 on 2022-10-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
