# Generated by Django 4.1.7 on 2023-03-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_remove_examresult_mark_remove_student_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='Mark',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
