# Generated by Django 4.1.7 on 2023-03-25 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_examresult_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='student_index',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Login.student'),
        ),
    ]
