# Generated by Django 3.2.12 on 2022-10-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20221029_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deoartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.FloatField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Department',
            new_name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
