# Generated by Django 3.2.12 on 2022-10-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20221029_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
