# Generated by Django 3.2.12 on 2022-10-29 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_auto_20221029_1602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deoartment',
            new_name='Department',
        ),
        migrations.AddField(
            model_name='course',
            name='Department',
            field=models.ManyToManyField(to='Login.Department'),
        ),
        migrations.AddField(
            model_name='course',
            name='Semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.ManyToManyField(to='Login.Department'),
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mark', models.CharField(choices=[('Pass', 'Passed'), ('Fail', 'Failed')], max_length=50, null=True)),
                ('Semester', models.IntegerField(null=True)),
                ('Course_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.course')),
                ('student_index', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.student')),
            ],
        ),
    ]
