# Generated by Django 4.1.1 on 2023-04-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_alter_examresult_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.IntegerField(default='0'),
        ),
    ]
