# Generated by Django 3.2.12 on 2022-10-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_auto_20221029_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='Code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
