# Generated by Django 4.1.1 on 2023-04-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=80)),
            ],
        ),
    ]
