# Generated by Django 4.1.1 on 2023-04-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_stuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stuser',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='index',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=80),
        ),
    ]
