# Generated by Django 4.1.1 on 2023-04-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_delete_stuser_alter_user_managers_user_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='index',
            field=models.CharField(max_length=90, unique=True),
        ),
    ]
