# Generated by Django 3.2.12 on 2022-11-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_auto_20221103_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='CGPA',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='GPA',
            field=models.IntegerField(null=True),
        ),
    ]
