# Generated by Django 3.2.12 on 2022-11-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_auto_20221104_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CGPA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.FloatField(null=True),
        ),
    ]
