# Generated by Django 4.1.1 on 2023-04-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_alter_user_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='index',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
