# Generated by Django 3.2.12 on 2022-11-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_auto_20221104_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Department',
        ),
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.CharField(choices=[('Computer Science', 'CS'), ('Information Technology', 'IT')], max_length=50, null=True),
        ),
    ]
