# Generated by Django 4.1.7 on 2023-09-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_remove_user_index_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student_index',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
