# Generated by Django 3.2.12 on 2022-11-04 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_auto_20221104_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Department',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.department'),
        ),
    ]
