# Generated by Django 4.1.7 on 2024-01-16 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_remove_examresult_id_alter_examresult_student_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Course1',
        ),
        migrations.CreateModel(
            name='Course5',
            fields=[
                ('Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Semester', models.IntegerField(null=True)),
                ('CreditHours', models.IntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course4',
            fields=[
                ('Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Semester', models.IntegerField(null=True)),
                ('CreditHours', models.IntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course3',
            fields=[
                ('Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Semester', models.IntegerField(null=True)),
                ('CreditHours', models.IntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course2',
            fields=[
                ('Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Semester', models.IntegerField(null=True)),
                ('CreditHours', models.IntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.department')),
            ],
        ),
    ]
