# Generated by Django 4.1.7 on 2024-01-16 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_rename_course_course1_course5_course4_course3_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course1',
            new_name='Course',
        ),
    ]
