# Generated by Django 3.2.12 on 2022-11-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_auto_20221104_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Computer Science', 'CS'), ('Information Technology', 'IT')], max_length=100, null=True),
        ),
    ]
