# Generated by Django 3.2.12 on 2022-11-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0014_auto_20221104_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ManyToManyField(
                default=1, null=True, to='Login.Department'),
        ),
    ]
