# Generated by Django 4.1.7 on 2024-01-16 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0014_rename_course_course1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='Course_code',
            new_name='Course_code1',
        ),
        migrations.RenameField(
            model_name='examresult',
            old_name='Mark',
            new_name='Mark1',
        ),
        migrations.AddField(
            model_name='examresult',
            name='Course_code2',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, to='Login.course2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='Course_code3',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, to='Login.course3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='Course_code4',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, to='Login.course4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='Course_code5',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, to='Login.course5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='Mark2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='Mark3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='Mark4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='Mark5',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
