# Generated by Django 3.2.12 on 2022-11-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0015_auto_20221104_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ManyToManyField(null=True, to='Login.Department'),
        ),
    ]
