# Generated by Django 4.1.7 on 2024-01-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0018_alter_course_name_alter_examresult_course_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course1',
            fields=[
                ('Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Semester', models.IntegerField(null=True)),
                ('CreditHours', models.IntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course2',
            fields=[
                ('Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Semester', models.IntegerField(null=True)),
                ('CreditHours', models.IntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course3',
            fields=[
                ('Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Semester', models.IntegerField(null=True)),
                ('CreditHours', models.IntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course4',
            fields=[
                ('Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Semester', models.IntegerField(null=True)),
                ('CreditHours', models.IntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course5',
            fields=[
                ('Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Semester', models.IntegerField(null=True)),
                ('CreditHours', models.IntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.department')),
            ],
        ),
        migrations.RenameField(
            model_name='examresult',
            old_name='Mark',
            new_name='Mark1',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='Course_code',
        ),
        migrations.AddField(
            model_name='examresult',
            name='Mark2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='Mark3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='Mark4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='Mark5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='examresult',
            table=None,
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='examresult',
            name='Course_code1',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, to='Login.course1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='Course_code2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.course2'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='Course_code3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.course3'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='Course_code4',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.course4'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='Course_code5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.course5'),
        ),
    ]
