# Generated by Django 3.2.12 on 2022-11-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0019_auto_20221107_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
