# Generated by Django 4.1.7 on 2024-01-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0019_course1_course2_course3_course4_course5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course2',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course3',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course4',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course5',
            name='department',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='Course_code1',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='Course_code2',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='Course_code3',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='Course_code4',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='Course_code5',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='Mark1',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='Mark2',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='Mark3',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='Mark4',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='Mark5',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='Semester',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='department',
        ),
        migrations.AddField(
            model_name='examresult',
            name='Course_code',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='examresult',
            name='Course_name',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='examresult',
            name='Mark',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.DeleteModel(
            name='Course1',
        ),
        migrations.DeleteModel(
            name='Course2',
        ),
        migrations.DeleteModel(
            name='Course3',
        ),
        migrations.DeleteModel(
            name='Course4',
        ),
        migrations.DeleteModel(
            name='Course5',
        ),
    ]
