# Generated by Django 4.1.7 on 2024-01-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0020_remove_course2_department_remove_course3_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='Requested',
            field=models.BooleanField(default=False),
        ),
    ]
