# Generated by Django 4.1.7 on 2024-01-18 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0021_examresult_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Mark', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='examresult',
            old_name='Requested',
            new_name='requested',
        ),
        migrations.AlterField(
            model_name='examresult',
            name='Course_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='Course_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='Mark',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Student_index', serialize=False, to='Login.student'),
        ),
    ]
