# Generated by Django 3.2.12 on 2022-11-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0021_alter_department_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
