# Generated by Django 4.1.1 on 2023-01-12 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0022_alter_department_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
    ]
