# Generated by Django 4.1.7 on 2024-01-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0022_course_rename_requested_examresult_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_index', to='Login.student'),
        ),
    ]
