# Generated by Django 4.1.1 on 2023-01-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0025_examresult_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='Semester',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
