# Generated by Django 4.1.7 on 2023-02-23 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Login', '0026_alter_examresult_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='highlighted',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
