# Generated by Django 4.1.7 on 2024-01-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0027_alter_examresult_student_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
