# Generated by Django 4.1.7 on 2024-01-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0028_alter_examresult_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
