# Generated by Django 4.1.7 on 2024-01-25 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0031_alter_examresult_student_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exams_Results', to='Login.student'),
        ),
    ]
