# Generated by Django 4.1.7 on 2023-02-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0032_alter_department_name_alter_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='student',
            name='owner',
        ),
    ]
