# Generated by Django 4.1.7 on 2024-01-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0033_alter_examresult_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='Semester',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
