# Generated by Django 4.1.7 on 2024-01-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0034_examresult_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='Semester',
            field=models.IntegerField(default=1),
        ),
    ]
